services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: rozliczkorki
      POSTGRES_PASSWORD: rozliczkorki
      POSTGRES_DB: rozliczkorki
    ports:
      - "5434:5432"
    volumes:
      - rozliczkorki_postgres_data:/var/lib/postgresql/data

volumes:
  rozliczkorki_postgres_data:
